# -*- coding: utf-8 -*-
import random


# Form implementation generated from reading ui file 'Calculator'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


def GetCalculator(UserGuess, start, end, ans):
    print(UserGuess, start, end, ans)
    if UserGuess == ans:
        return [True]
    if UserGuess < start or UserGuess > end:
        return [False]

    if start <= UserGuess <= ans:
        start = UserGuess
        return [False, start, end]
    if ans <= UserGuess <= end:
        end = UserGuess
        return [False, start, end]

def TipForUser(start, end, ans):
    if start < ans - 1:
        start = random.randint(start + 1, ans - 1)
    if end > ans + 1:
        end = random.randint(ans + 1, end - 1)

    return [start, end]

if __name__ == '__main__':
    print(TipForUser(3, 7, 5))